"""empty message

Revision ID: 069f0ca00172
Revises: 640e82a8b51d
Create Date: 2016-08-09 20:47:34.308239

"""

# revision identifiers, used by Alembic.
revision = '069f0ca00172'
down_revision = '640e82a8b51d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('app_version', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'app_version')
    ### end Alembic commands ###
