"""empty message

Revision ID: 44b093d395b0
Revises: 498ab45bc92d
Create Date: 2016-07-21 15:17:21.277334

"""

# revision identifiers, used by Alembic.
revision = '44b093d395b0'
down_revision = '498ab45bc92d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('fingerprint', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'practice', ['fingerprint'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice', type_='unique')
    op.drop_column('practice', 'fingerprint')
    ### end Alembic commands ###
