"""empty message

Revision ID: d606efcaf6a6
Revises: 1da105b7c67f
Create Date: 2016-07-10 21:25:09.949147

"""

# revision identifiers, used by Alembic.
revision = 'd606efcaf6a6'
down_revision = '1da105b7c67f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('reason_for_creation', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'reason_for_creation')
    ### end Alembic commands ###
